// <auto-generated />
namespace BridgingTheGap.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Update26 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update26));
        
        string IMigrationMetadata.Id
        {
            get { return "202201311125150_Update2.6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
