// <auto-generated />
namespace BridgingTheGap.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class update28 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update28));
        
        string IMigrationMetadata.Id
        {
            get { return "202202040042274_update2.8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
