// <auto-generated />
namespace BridgingTheGap.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class GuidAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GuidAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202201210320185_GuidAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
