// <auto-generated />
namespace BridgingTheGap.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class update27 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update27));
        
        string IMigrationMetadata.Id
        {
            get { return "202202032257587_update2.7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
